/**
 * OAuth client ids for Google sign-in. Generated by scripts/sync-oauth.js
 * from the Firebase config files; do not edit by hand.
 */
export const oauthConfig = {
  /** OAuth 2.0 web client id (type 3 in google-services.json). Required for Firebase credential exchange. */
  googleWebClientId: '499315426030-fd6riid8tgkmvugh55fup0iodf4nrll1.apps.googleusercontent.com',
  /** iOS client id from GoogleService-Info.plist. */
  googleIosClientId: '499315426030-nmkbm3orugbapskateq3vo1moe3njg9h.apps.googleusercontent.com',
};
