import {
  Banknote,
  Bell,
  BellOff,
  Book,
  Bookmark,
  CalendarDays,
  ChartColumn,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleArrowRight,
  CircleCheck,
  CirclePlus,
  CircleX,
  ClockArrowLeft,
  DollarSign,
  Dumbbell,
  Ellipsis,
  EllipsisVertical,
  Eye,
  EyeOff,
  FaceSlightlySmiling,
  Flame,
  Footprints,
  GripVertical,
  Heart,
  House,
  Info,
  KeyRound,
  Lightbulb,
  List,
  LogOut,
  Mail,
  Medal,
  MessageCircle,
  Minus,
  Moon,
  Play,
  Plus,
  Presentation,
  Scale,
  Settings,
  SquarePen,
  ThumbsDown,
  ThumbsUp,
  Timer,
  TriangleAlert,
  Trophy,
  User,
  Users,
  Wrench,
  X,
} from 'lucide-react-native';

/**
 * Named icons used across the app, all from Lucide. Render them with
 * `<Icon icon={generalIcons.dumbbell} />`.
 */
export const directionIcons = {
  angleDown: ChevronDown,
  angleLeft: ChevronLeft,
  angleRight: ChevronRight,
  angleUp: ChevronUp,
  leftCaret: ChevronLeft,
  rightArrow: CircleArrowRight,
  rightCaret: ChevronRight,
};

export const generalIcons = {
  bell: Bell,
  bellSlash: BellOff,
  book: Book,
  bookmarkOutline: Bookmark,
  bookmarkFilled: Bookmark,
  bulletPoint: Circle,
  calendarDay: CalendarDays,
  check: Check,
  clock: ClockArrowLeft,
  comment: MessageCircle,
  dollar: DollarSign,
  dumbbell: Dumbbell,
  ellipsis: Ellipsis,
  ellipsisVertical: EllipsisVertical,
  envelope: Mail,
  error: CircleAlert,
  eye: Eye,
  eyeSlash: EyeOff,
  flame: Flame,
  gear: Settings,
  grip: GripVertical,
  heart: Heart,
  info: Info,
  key: KeyRound,
  lightbulb: Lightbulb,
  list: List,
  medal: Medal,
  minus: Minus,
  moneyBills: Banknote,
  moon: Moon,
  penToSquare: SquarePen,
  personRunning: Footprints,
  personTeaching: Presentation,
  play: Play,
  plus: Plus,
  scale: Scale,
  screwdriverWrench: Wrench,
  signOut: LogOut,
  simpleChart: ChartColumn,
  success: CircleCheck,
  thumbsDownFilled: ThumbsDown,
  thumbsDownOutline: ThumbsDown,
  thumbsUpFilled: ThumbsUp,
  thumbsUpOutline: ThumbsUp,
  timer: Timer,
  trophy: Trophy,
  user: User,
  users: Users,
  warning: TriangleAlert,
  xMark: X,
  xMarkCircle: CircleX,
};

export const tabIcons = {
  home: House,
  workout: Dumbbell,
  stats: ChartLine,
  log: CirclePlus,
  social: FaceSlightlySmiling,
  profile: User,
};
