#!/usr/bin/env node
/**
 * Reads the Google OAuth client ids out of the Firebase config files and
 * writes data/auth/oauthConfig.ts. Run after re-downloading the configs
 * once the Google provider is enabled in the Firebase console.
 */
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const plist = fs.readFileSync(path.join(root, 'ios/GoogleService-Info.plist'), 'utf8');
const ios = (plist.match(/<key>CLIENT_ID<\/key>\s*<string>([^<]+)<\/string>/) || [])[1] || '';
let web = '';
try {
  const json = JSON.parse(fs.readFileSync(path.join(root, 'android/app/google-services.json'), 'utf8'));
  for (const client of json.client || []) {
    for (const oc of client.oauth_client || []) if (oc.client_type === 3) web = oc.client_id;
  }
} catch (e) {
  console.warn('google-services.json not readable:', e.message);
}
const out = `/**
 * OAuth client ids for Google sign-in. Generated by scripts/sync-oauth.js
 * from the Firebase config files; do not edit by hand.
 */
export const oauthConfig = {
  /** OAuth 2.0 web client id (type 3 in google-services.json). Required for Firebase credential exchange. */
  googleWebClientId: '${web}',
  /** iOS client id from GoogleService-Info.plist. */
  googleIosClientId: '${ios}',
};
`;
fs.writeFileSync(path.join(root, 'data/auth/oauthConfig.ts'), out);
console.log(`web client id: ${web ? 'found' : 'MISSING'}; iOS client id: ${ios ? 'found' : 'MISSING'}`);
